# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rabbit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Rabbit
  pod 'Masonry'
  pod 'NullSafe'
  pod 'Reachability'
  pod 'AFNetworking'
  # pod 'WCDB', git: 'https://github.com/Tencent/wcdb.git' , branch: 'master'
  pod 'YYModel'
  pod 'WCDB'
  # pod 'YYKit'
  pod 'MJRefresh', '3.1.15.1'
  # pod 'MBProgressHUD'
  pod 'SDWebImage'
  # pod 'ZJScrollPageView'
  pod 'IQKeyboardManager'
  pod 'UITableView+FDTemplateLayoutCell'


end
